language: php

php:
- '7.1'
env:
  global:
  - ZIP_FILENAME=bmlt-export-build${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
  - S3_BUCKET=archives.bmlt.app
  - S3_KEY=bmlt-export
jobs:
  include:

  - stage: lint
    install:
    - composer install
    script:
    - find . -name "*.php" ! -path '*/vendor/*' -print0 | xargs -0 -n1 -P8 php -l
    - vendor/squizlabs/php_codesniffer/bin/phpcs --warning-severity=6 --standard=PSR2 --ignore=vendor --extensions=php --report=summary ./
  - stage: zip file
    env:
    - BUILD_DIR=build
    - DIST_DIR_S3=dist/s3
    - DIST_DIR_GITHUB=dist/github
    - GITHUB_RELEASE_FILENAME=bmlt-export.zip
    - PLUGIN="bmlt-export"
    - MAINFILE="bmlt-export.php"
    script:
    - find ./ -type d | xargs chmod 755
    - find ./ -name '*.php' | xargs chmod 644
    - zip -r $ZIP_FILENAME ./ -x "*.git*" -x "*.editorconfig*" -x "*.travis.yml*" -x "*assets*" -x "*vendor*" -x "composer.*" -x "*.gitattributes" && mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
    before_deploy:
    - mkdir -p $DIST_DIR_S3 && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_S3/$ZIP_FILENAME
    - mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
    - curl -LO https://raw.githubusercontent.com/bmlt-enabled/bmlt-wordpress-deploy/master/deploy-wordpress.sh
    - chmod +x deploy-wordpress.sh
    deploy:
    - provider: s3
      access_key_id: AKIAI7JHYFA6DI3WYP5A
      secret_access_key:
        secure: kT408WY+NTy9hzYuccSXTLQkpi1SRz/kT/hsIBq6C3T9XuvBQ5r1W8qghqnXcNOsE2ns0q+GCIyUUASoa4UmXoKW4PLDJLGeU+q/KacawoIjBZdjG/u4xPWQA7aEWAJpvI9WdB1LOTDdhxNgrxO0YBixKJ5A2rL8R/ophdEaLJFFWiCHKoXFMix56sq2XabCnZ9yk7IIcmxEBIPkh6wnaW4RROvlP5kpQUyA1mkDXKEGlvC7PdnJSkjVNsrOLhykKZSHZNhp7pVtcNF2tz88UZHDchVWFZl0qZlrR+VxfjydtoSggMi3NbKZeb9SOecI2K13k91mfbPHHA5rJYSzpCmUJBCwpkGIVdjDOwOw7O3dXu//EGfbSacGy/jhR7LSjtY9EnDlG0ggOjJMfsXMyd/ujU99HLRHtCWnw9Lg3o2tHeRm9o10VlWdBD5/qnRkvNs3O5D0KORhxk3g6AqMFMExCu2CjN0u2LhJS5D5QPGOabVi4dMaF0ua5hgvZnvRznA7GCDvD+919qwSQ37+K4cYVcvqh2dmqvYLKsW93W6wX7NBgORJU3VfN146XkkJ3p+eP+fPqixEX2TxQL14LpDwIMEDyik6o8U3jlc44odOyQj8NdvKCy6VEFszZE3NfyeuY6FL/8I0iiXOKAYZpMpT6xVVBFMCffhKj50EDRI=
      bucket: "$S3_BUCKET"
      local_dir: "$DIST_DIR_S3"
      upload-dir: "$S3_KEY"
      skip_cleanup: true
      on:
        all_branches: true
    - provider: releases
      api_key:
        secure: 0MSR/nrP0OZUr5nd9URFoRGlLkmIiY6qsLxi95UZEL6JbeC51BpmnDVS7fQDfBIwrmVNGhzCJ5hUE1+PAYptPC4pLkwcEmYmRYkM6wvlexLbfYnE/aLtwPsd+EdVY53fg5XDxnD3pMBKCBgfTlj37SfeaGbx5zHluJmo5XnLsYV9nAR/R1WKo92f7xSiFsXX1FtAuRhgDk+pWRM8quY5A2Do8eyeApxzpdOzhKk4YbT64W8w0PiRxATMgYl7GjE0WA7KpmABlun16O7H8ISxUqftBlUyo5cFLDhMtCW8MiESN5NCuZVkTuVIgq1DwWfilVuHxPPB8gjt57J/h0+QctM8ZBXFiHuXi9PRklH7KcPD1hlMIDuIGe9w5egcXUrdZfGMgr/PW6iSs2vJ6Pf3bMO1DIeZCzTrYGmJ6YqNGbS/+hqJMq1dAZd+RS2dlio2KOa+omZoPDF4yd4+jVMbtWaIqzKF4ldYyg3Pa78y+gGgIwbZ7psOcbrt2OFaNpeC/RW1oHVdBe9esS23R5h3nu2iYgKljwb8ByAMu8fj9c5zCSPvjgcyW3gJYwaCDu6rLRBFC1IveXIv9Ld+doqqzdUrc5VaJlhExaqk8WThSISQvWsV+38UROJZCmGFdOxn2Ja1ha0dHGi9x0aQsoN3K7/ffEhXn+9GcMM8+48MLmE=
      file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
      skip_cleanup: true
      name: "$TRAVIS_TAG"
      on:
        tags: true
        condition: $TRAVIS_TAG != *beta*
    - provider: releases
      api_key:
        secure: 0MSR/nrP0OZUr5nd9URFoRGlLkmIiY6qsLxi95UZEL6JbeC51BpmnDVS7fQDfBIwrmVNGhzCJ5hUE1+PAYptPC4pLkwcEmYmRYkM6wvlexLbfYnE/aLtwPsd+EdVY53fg5XDxnD3pMBKCBgfTlj37SfeaGbx5zHluJmo5XnLsYV9nAR/R1WKo92f7xSiFsXX1FtAuRhgDk+pWRM8quY5A2Do8eyeApxzpdOzhKk4YbT64W8w0PiRxATMgYl7GjE0WA7KpmABlun16O7H8ISxUqftBlUyo5cFLDhMtCW8MiESN5NCuZVkTuVIgq1DwWfilVuHxPPB8gjt57J/h0+QctM8ZBXFiHuXi9PRklH7KcPD1hlMIDuIGe9w5egcXUrdZfGMgr/PW6iSs2vJ6Pf3bMO1DIeZCzTrYGmJ6YqNGbS/+hqJMq1dAZd+RS2dlio2KOa+omZoPDF4yd4+jVMbtWaIqzKF4ldYyg3Pa78y+gGgIwbZ7psOcbrt2OFaNpeC/RW1oHVdBe9esS23R5h3nu2iYgKljwb8ByAMu8fj9c5zCSPvjgcyW3gJYwaCDu6rLRBFC1IveXIv9Ld+doqqzdUrc5VaJlhExaqk8WThSISQvWsV+38UROJZCmGFdOxn2Ja1ha0dHGi9x0aQsoN3K7/ffEhXn+9GcMM8+48MLmE=
      file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
      skip_cleanup: true
      name: "$TRAVIS_TAG"
      prerelease: true
      on:
        tags: true
        condition: $TRAVIS_TAG =~ "beta"
    - provider: script
      script: ./deploy-wordpress.sh
      skip_cleanup: true
      on:
        tags: true
notifications:
  slack:
    rooms:
    - secure: bmoIugz9sorNakDw7LnfC3iB7a4CnhuZeZBAVxefSoqipbZAGLoA86pSaDwSK3kNsCRAUXyHJ0pBxxJuCO5jrQKhl9TNBFQQ60KPvn3LQj9OXXTSHp4qoqBytipQGyjeqySu4fJt8Lc0u8FQ0qinxn21qF7K7c54aygVKQd+nxf/+9rVzSOJIY+c6UEBb9FwKfHl9cOJy8nTHYPNl0ZbQaYVS1gvyOV2jzrlurOXb0t2xYs2W9EOAjUd2E4ZVaD8EEyRZ9zcvy8ne41qZGBLMJjHZo6TdN4x0AdEYiITst5fKj+YILNCaVQMyURu5h65RPVXyjZ/eIOUixSt1EOpMTxWcRiDn3H7B2F7eEUIXyo/c5x1AEWEQFLGK+/PEqWx/zaBG0rJJdzVbLaqet2kg5piy+f84EBCZiXm7CZIYPMSjLJo9AJDcY9iSRgvpRnkSagHZAgMILNut53aNPd8i3FoOeycPwux/KDQpSz0uIpn4xu26VY0bzxJ8N27VugUhmNhLCN05Hgw8GoDjEoh4EgPPsdNVzXT4mzpjx2GfhRZOm/78LUSDB/w3oIAEPzRFfhberBAo0l2w9T5+Ynbw9yyquYgNUOW/nMhbwqOPbWqndHa8Xume0DXp2COHEqoSZx4gDIIRRKjKdsrFjjasWB5K7IQXQfBoiGAL7EscNA=
    on_success: change
  email: false
